services:
    rmcgirr83.sfpo.listener:
        class: rmcgirr83\sfpo\event\listener
        arguments:
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '@rmcgirr83.sfpo.core.trim'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    rmcgirr83.sfpo.core.trim:
        class: rmcgirr83\sfpo\core\sfpo_trim
