services:
    rmcgirr83.sfpo.listener:
        class: rmcgirr83\sfpo\event\listener
        arguments:
            - '@config'
            - '@content.visibility'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@template'
            - '@text_formatter.s9e.utils'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
